language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

sudo: false
dist: trusty

matrix:
  include:
    - php: 5.3.3
      dist: precise

before_script:
  - '[[ "$TRAVIS_PHP_VERSION" == 5.3* ]] && composer config -g -- disable-tls true || true'
  - '[[ "$TRAVIS_PHP_VERSION" == 5.3* ]] && composer config -g -- secure-http false || true'
  - if [[ $(phpenv version-name) == '5.6' ]]; then composer require php-coveralls/php-coveralls:^2.1 -n ; fi
  - if [[ $(phpenv version-name) != '5.6' ]]; then composer install -n ; fi

script:
  - if [[ $(phpenv version-name) == '5.6' ]]; then $TRAVIS_BUILD_DIR/vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ $(phpenv version-name) != '5.6' ]]; then $TRAVIS_BUILD_DIR/vendor/bin/phpunit ; fi

after_script:
  - if [[ $(phpenv version-name) == '5.6' ]]; then php vendor/bin/coveralls -v ; fi
